### PR TITLE
added aligner loss

### PR DESCRIPTION
**Pull request by manmay-nakhashi**

### CODE REVIEW

**Comment by lucidrains** [comment]
@manmay-nakhashi hey! yes i was scratching my head at where that was used this morning

thank you! 🙏 

small conflict since i just committed something in 😓

**Comment by manmay-nakhashi** [comment]
i'll fix it no worries

**Comment by manmay-nakhashi** [comment]
@lucidrains fixed now

**Comment by lucidrains** [comment]
@manmay-nakhashi 🚀 💯

**Pull request merged**
